# Related work

## Neighborhood classification

There is a large body of literature that seeks to apply quantitative methods to 
describe or classify urban environments. In 2011, Urban Geography released a 
special issue devoted to neighborhood classification approaches, including a 
review of neighborhood classification work that had been done to date [@reibel2011classification];
a study identifying five distinct neighborhood types in Cleveland and 
demonstrating how locations transition among types [@mikelbank2011neighborhood];
a method for identifying ethnic neighborhoods [@logan2011identifying]; and an
analysis of New Urban developments that classifies them by how well they meet the 
ambitions of the New Urbanism movement [@trudeau2011suburbs]. A common approach to 
classifying neigborhoods has been to employ factor analysis (principal
component analysis) to reduce a large number
of variables into a smaller set of factors (or principal components), followed by
cluster analysis to group neighborhoods sharing similar characteristics [@voulgaris_synergistic_2016; @chow_differentiating_1998; @li_neighborhood_2009; @shay_automobiles_2007; @song_quantitative_2007; @song_how_2008; @vicino_typology_2011]. 
Although the purpose of neighborhood classification studies is to develop a set 
of categorical neighborhood types, the initial factor analysis step yields a set 
of indices that can be used as continuous variables describing various dimensions 
of neighborhood characteristics.

## Quantification of sprawl

In general, neighborhood classification studies have differentiated between 
neighborhoods with a more urban character and those with a more suburban 
character. Indeed this is often the explicit purpose of such analyses. A 
related body of work has specifically sought to quanitify sprawl. @hamidi2015measuring
offers a helpful review of the early work on this topic, noting that early studies
emphasized density as a measure of sprawl and that some used satellite imagery 
to incorporate parameters like fragmentation and fractal dimension. @ewing_measuring_2002
have developed a widely-cited measure of sprawl using principal component analysis
to develop indices for four separate dimensions of sprawl (density, land-use diversity, 
centering, and street accessibility) and averaging them (with equal weights) to generate
a single overall sprawl index. @hamidi2015measuring later repeated this method with 
updated data and have published a dataset of county-level and tract-level values
for the resulting sprawl index. 

## Conceptualizing urban quality at the site level

Urban quality may be comparatively measured at the city, neighborhood, and site scales but each of these scales yield different decision-making capacities, and for different stakeholders. Regional planning decisions and high-level policy initiatives operate at the scale of the city; zoning and planning operates at the level of the neighborhood; real estate development and incremental changes to the design and use of urban fabric and form occur at the site level.

Because decisions that shape urban quality are often made at the site level, and because neighborhoods can often host a wide diversity of conditions from one edge to another, a parcel-level metric for differentiating among adjacent sites and urban blocks within the same neighborhood would be useful. 


## Barriers to site-level urban quality evaluation

Because widely available and reliable data for urban classification across many urban places often exists at the levels of the census tract and above, methods for conceptualizing urban quality at the site level are challenging. Moving from the neighborhood level to the site level requires a jump from demographic, econometric, and geospatial data to the scale of human perception. This jump requires design as well as planning expertise. The lack of systematically available data at the site level is due to a variety of factors including privacy and the diverse types of data, including image-based formats, required to address local identity and human perception. Additionally, some variables have no meaning at the site level. While creating buffers around a site might address this to some degree, it requires the existence of complimentary site-level data as well.

Methods for understanding site-level experience and conditions have begun to emerge over the past decade, and reliable data is increasingly available through both open public sources and private or open mapping platforms.   Groups such as the Trust for Public Land have utilized site level analysis to create applications such as the ParkScore index and related the ParkServe mapping application to broaden understanding of hyper-local conditions and equitable access to open space. Hidalgo et al. [2016] have utilized Google Street view and computer vision applications to approach questions of urban perception at the site level in their PlacePulse project. While the work is not informed by sophisticated urban planning and design expertise, it provides a promising technical method for accessing and utilizing emerging web-based image data alongside computer vision through the use of an application programming interface (API).
