# Relating Indices to Values

There is some alignment between the qualitative (values-driven) categories that emerged from the workshop and the indices produced by the quantitative analysis. This alignment is strongest surrounding variables related to connectivity. High connectivity to jobs and local resources relates (see factor loading) within the quantitative analysis; workshop participants identified and grouped the same variables as relevant to urban qualities related to both socio-economic viability (job access) and environmental sustainability (reduced carbon expenditure on commutes). Sites that are highly connected to walkable resources and jobs (via bike or transit) are viewed by the experts as good places to locate future housing; they are presented in the factor analysis under the categories of “walkable” and “dense.”

We would also like to address the quantitative results in relationship to the values of the experts around the issue of low-income and workforce housing as it intersects with urban change or gentrification. The quantitative analysis currently enables an understanding of where development is likely to occur based upon trends such as building permits. Both the quantitative outcomes and our experiential knowledge of the study area show that these areas tend to be highly walkable, diverse, and connected. This outcome points to the intersection of desirability and feasibility but also raises the issue of gentrification, which is a concern of the experts. It is worth noting that our lived experience with study area indicates that the “walkable” index is strongly related to high property values and demographic variables such as race and income. 

We would also like to note our observations on the quantitative analysis from the perspective of lived experience, using a neighborhood called the Hill District area as an example. The Hill District, an area that is highly proximate to downtown Pittsburgh (via bike) and that also suffers from historic disinvestment and marginalization, is shown within the quantitative analysis as high in “density” and “drivability,” moderate in “diversity,” and low in “walkability.” Our experience in the study area suggests that it is a highly suitable area for future housing in that it is central, close to many jobs, and has many vacant parcels of land. However, the lack of walkable resources – such as grocery stores and libraries – makes it less attractive as a profitable investment.

This potential divergence between long-term suitability and short-term suitability (or immediate market viability) is notable. While the Hill District is high in qualities related to “density” it would likely require long-term and substantial public investment and attention to make it feasible for new housing development in the short-term. In the future, we would like to explore the relationship between “density” and “walkability” as indicators of long-term and short-term potential as they relate to housing development and private vs. public stakeholders. In general, more consideration is needed into the composition and meaning of each of the indices in relationship to the disciplinary and civic values that emerged through the workshops. The “density” index is of particularly high interest because of its ability to identify potentially suitable sites that do not always conform to obvious existing market opportunities.

We not that serious consideration needs to be given to the relationship between quantitative results and disciplinary values (qualitative workshop data) as it translates into a practical tool for understanding existing urban quality and citing future housing or focusing housing-related policy. For example, future research may engage the buffering method and income data to focus on the site-based prioritization of housing for an existing local median income to enable stakeholders to understand site-level quality in relationship to a recommendation for future housing driven by the value of a social sustainability and equity. This is an area of friction between the quantitative analysis and workshop outcomes that can be explored in the future through the translation of quantitative analysis into practical application by stakeholders via values-driven data visualization and interaction design.
